#!/usr/bin/env python3
"""todo-to-issue — scan code for TODO/FIXME comments and convert to GitHub Issue format.

Usage:
    python todo_to_issue.py PATH [PATH ...] [--tags T1,T2] [--assignee USER] [--json] [--output FILE]

Generates GitHub Issue Markdown from code annotations.
"""

import argparse
import json
import os
import re
import sys

SKIP_DIRS = {".git", "node_modules", "vendor", "__pycache__", "__pypackages__", ".venv", "venv"}
SCAN_EXTS = {".py", ".js", ".ts", ".jsx", ".tsx", ".go", ".java", ".rb", ".sh",
             ".c", ".cpp", ".h", ".hpp", ".cs", ".php", ".rs", ".swift", ".kt",
             ".scala", ".m", ".mm", ".lua", ".r", ".R", ".jl", ".ex", ".exs",
             ".erl", ".hs", ".clj", ".vue", ".svelte"}

DEFAULT_TAGS = ["TODO", "FIXME", "HACK", "XXX", "BUG", "NOTE"]

TAG_LABELS = {
    "TODO": "enhancement",
    "FIXME": "bug",
    "HACK": "technical debt",
    "XXX": "wontfix",
    "BUG": "bug",
    "NOTE": "documentation",
}

# Pattern: optional comment prefix, tag, optional colon, content
TAG_PATTERN = re.compile(
    r'(?:^|\s)(?:#|//|<!--|;\s*|/\*)\s*({tags})\s*:?\s*(.*?)(?:\*/|-->|$)',
    re.IGNORECASE
)


def _build_pattern(tags):
    """Build regex pattern from tag list."""
    tag_alt = "|".join(re.escape(t) for t in tags)
    return re.compile(
        r'(?:^|\s)(?:#\s*|//\s*|<!--\s*|;\s*|/\*\s*)(' + tag_alt + r')\s*:?\s*(.*?)(?:\s*\*/|\s*-->|$)',
        re.IGNORECASE
    )


def scan_file(filepath, pattern):
    """Scan a single file for tag annotations."""
    results = []
    try:
        with open(filepath, encoding="utf-8", errors="replace") as f:
            for line_num, line in enumerate(f, 1):
                m = pattern.search(line)
                if m:
                    tag = m.group(1).upper()
                    text = m.group(2).strip()
                    if not text:
                        text = line.strip()
                    results.append({
                        "file": filepath,
                        "line": line_num,
                        "tag": tag,
                        "text": text,
                    })
    except (OSError, UnicodeDecodeError):
        pass
    return results


def _iter_targets(paths):
    for p in paths:
        if os.path.isfile(p):
            yield p
        elif os.path.isdir(p):
            for root, dirs, files in os.walk(p):
                dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
                for fn in files:
                    if os.path.splitext(fn)[1].lower() in SCAN_EXTS:
                        yield os.path.join(root, fn)


def format_issue(todo, repo_url=None, assignee=None):
    """Format a single TODO as a GitHub Issue body."""
    tag = todo["tag"]
    text = todo["text"]
    filepath = todo["file"]
    line = todo["line"]
    label = TAG_LABELS.get(tag, "enhancement")

    title = f"[{tag}] {text}"

    body_lines = [
        f"## {tag}: {text}",
        "",
        f"**File:** `{filepath}`",
        f"**Line:** {line}",
    ]

    if repo_url:
        # Assume GitHub URL structure
        body_lines.append(f"**Link:** [{filepath}:{line}]({repo_url}/blob/main/{filepath}#L{line})")

    body_lines.append("")
    body_lines.append("---")
    body_lines.append(f"*Auto-generated by todo-to-issue*")

    issue = {
        "title": title,
        "body": "\n".join(body_lines),
        "labels": [label],
        "tag": tag,
        "file": filepath,
        "line": line,
        "text": text,
    }

    if assignee:
        issue["assignee"] = assignee

    return issue


def main():
    ap = argparse.ArgumentParser(
        description="Scan code for TODO/FIXME comments and convert to GitHub Issue format."
    )
    ap.add_argument("paths", nargs="+", help="files or directories to scan")
    ap.add_argument("--tags", default=",".join(DEFAULT_TAGS),
                    help=f"comma-separated tags to scan (default: {','.join(DEFAULT_TAGS)})")
    ap.add_argument("--assignee", default=None,
                    help="default assignee for generated issues")
    ap.add_argument("--repo-url", default=None,
                    help="repository URL for file links in issue bodies")
    ap.add_argument("--json", action="store_true",
                    help="output JSON results")
    ap.add_argument("--output", "-o", default=None,
                    help="write Markdown issues to file")
    args = ap.parse_args()

    tags = [t.strip().upper() for t in args.tags.split(",")]
    pattern = _build_pattern(tags)

    all_todos = []
    for fp in _iter_targets(args.paths):
        all_todos.extend(scan_file(fp, pattern))

    issues = [format_issue(t, repo_url=args.repo_url, assignee=args.assignee) for t in all_todos]

    if args.json:
        print(json.dumps(issues, indent=2, ensure_ascii=False))
    else:
        md_parts = []
        for issue in issues:
            part = f"### {issue['title']}\n\n"
            part += issue["body"]
            part += f"\n\n**Labels:** {', '.join(issue['labels'])}"
            if issue.get("assignee"):
                part += f"\n**Assignee:** {issue['assignee']}"
            md_parts.append(part)

        output = "\n\n---\n\n".join(md_parts)

        if args.output:
            os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(output)
            print(f"Written {len(issues)} issue(s) to {args.output}")
        else:
            if output:
                print(output)
            else:
                print("No TODO/FIXME comments found.")

    if not issues:
        print(f"No annotations found for tags: {', '.join(tags)}", file=sys.stderr)


if __name__ == "__main__":
    main()
